.TH BLUETOOTH_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
bluetooth_scan \- Script para realizar escaneos de dispositivos Bluetooth
.SH SYNOPSIS
.B bluetooth_scan
.SH DESCRIPCIÓN
Este script realiza un escaneo de dispositivos Bluetooth cercanos.

.SH EJEMPLOS
.B
bluetooth_scan

.SH AUTOR
Desarrollado por el equipo de red teaming.
