.TH BURP_SUITE_SETUP 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
burp_suite_setup \- Script para configurar Burp Suite
.SH SYNOPSIS
.B burp_suite_setup
.SH DESCRIPCIÓN
Este script inicia y configura Burp Suite.

.SH EJEMPLOS
.B
burp_suite_setup

.SH AUTOR
Desarrollado por el equipo de red teaming.
