.TH ENUM4LINUX_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
enum4linux_scan \- Script para realizar escaneos Enum4linux
.SH SYNOPSIS
.B enum4linux_scan
.RI [ opciones ] " <target>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Enum4linux en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo del escaneo.

.SH EJEMPLOS
.B
enum4linux_scan 192.168.1.1

.SH AUTOR
Desarrollado por el equipo de red teaming.
