.TH IMPACKET_ATTACK 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
impacket_attack \- Script para realizar ataques Impacket
.SH SYNOPSIS
.B impacket_attack
.RI [ opciones ] " <target> <command>"
.SH DESCRIPCIÓN
Este script realiza un ataque Impacket en el objetivo especificado usando el comando proporcionado.

.SH OPCIONES
.TP
.BI \-t
