.TH JOHN_RIPPER 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
john_ripper \- Script para crackeo de hashes con John the Ripper
.SH SYNOPSIS
.B john_ripper
.RI [ opciones ] " <hashfile>"
.SH DESCRIPCIÓN
Este script realiza un crackeo de hashes en el archivo especificado usando John the Ripper.

.SH OPCIONES
.TP
.BI \-f ", \--hashfile" " <hashfile>"
Especifica el archivo de hashes a crackear.

.SH EJEMPLOS
.B
john_ripper hashes.txt

.SH AUTOR
Desarrollado por el equipo de red teaming.
