.TH KATANA_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
katana_scan \- Script para realizar escaneos Katana
.SH SYNOPSIS
.B katana_scan
.RI [ opciones ] " <url>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Katana en la URL especificada.

.SH OPCIONES
.TP
.BI \-u ", \--url" " <url>"
Especifica la URL objetivo para el escaneo.

.SH EJEMPLOS
.B
katana_scan http://example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
