.TH KISMET_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
kismet_scan \- Script para realizar escaneos Kismet
.SH SYNOPSIS
.B kismet_scan
.RI [ opciones ] " <interface>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Kismet en la interfaz especificada.

.SH OPCIONES
.TP
.BI \-i ", \--interface" " <interface>"
Especifica la interfaz de red a usar para el escaneo.

.SH EJEMPLOS
.B
kismet_scan wlan0

.SH AUTOR
Desarrollado por el equipo de red teaming.
