.TH MASSCAN_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
masscan_scan \- Script para realizar escaneos Masscan
.SH SYNOPSIS
.B masscan_scan
.RI [ opciones ] " <target> <port>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Masscan en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo del escaneo.
.TP
.BI \-p ", \--port" " <port>"
Especifica el puerto a escan
