.TH METASPLOIT_SETUP 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
metasploit_setup \- Script para configurar Metasploit
.SH SYNOPSIS
.B metasploit_setup
.SH DESCRIPCIÓN
Este script inicia y configura Metasploit.

.SH EJEMPLOS
.B
metasploit_setup

.SH AUTOR
Desarrollado por el equipo de red teaming.
