.TH MIMIKATZ_ATTACK 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
mimikatz_attack \- Script para ejecutar Mimikatz en el objetivo
.SH SYNOPSIS
.B mimikatz_attack
.RI [ opciones ] " <target>"
.SH DESCRIPCIÓN
Este script ejecuta Mimikatz en el objetivo especificado para extraer credenciales.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo del ataque.

.SH EJEMPLOS
.B
mimikatz_attack 192.168.1.10

.SH AUTOR
Desarrollado por el equipo de red teaming.
