.TH NMAP_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
nmap_scan \- Script para realizar escaneos Nmap
.SH SYNOPSIS
.B nmap_scan
.RI [ opciones ] " <target>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Nmap en el objetivo especificado usando las opciones proporcionadas.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo del escaneo.
.TP
.BI \-o ", \--options" " <opciones>"
Especifica las opciones de Nmap (por defecto: -sV -sC).

.SH EJEMPLOS
.B
nmap_scan 192.168.1.1

.SH AUTOR
Desarrollado por el equipo de red teaming.
