.TH NUCLEI_SCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
nuclei_scan \- Script para realizar escaneos Nuclei
.SH SYNOPSIS
.B nuclei_scan
.RI [ opciones ] " <target>"
.SH DESCRIPCIÓN
Este script realiza un escaneo Nuclei en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo del escaneo.

.SH EJEMPLOS
.B
nuclei_scan http://example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
