.TH RECON 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
recon \- Script para realizar tareas de reconocimiento
.SH SYNOPSIS
.B recon
.RI [ opciones ] " <target_domain>"
.SH DESCRIPCIÓN
Este script realiza tareas de reconocimiento en el dominio objetivo especificado.

.SH OPCIONES
.TP
.BI \-d ", \--domain" " <target_domain>"
Especifica el dominio objetivo para el reconocimiento.

.SH EJEMPLOS
.B
recon example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
