.TH RESPONDER_ATTACK 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
responder_attack \- Script para realizar ataques Responder
.SH SYNOPSIS
.B responder_attack
.RI [ opciones ] " <interface>"
.SH DESCRIPCIÓN
Este script realiza un ataque Responder en la interfaz especificada.

.SH OPCIONES
.TP
.BI \-i ", \--interface" " <interface>"
Especifica la interfaz para el ataque.

.SH EJEMPLOS
.B
responder_attack eth0

.SH AUTOR
Desarrollado por el equipo de red teaming.
