.TH VEIL_EVASION 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
veil_evasion \- Script para iniciar Veil-Evasion
.SH SYNOPSIS
.B veil_evasion
.SH DESCRIPCIÓN
Este script inicia Veil-Evasion para la creación de payloads.

.SH OPCIONES
No tiene opciones.

.SH EJEMPLOS
.B
veil_evasion

.SH AUTOR
Desarrollado por el equipo de red teaming.
