.TH WPSCAN 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
wpscan \- Script para realizar escaneos WPScan
.SH SYNOPSIS
.B wpscan
.RI [ opciones ] " <url>"
.SH DESCRIPCIÓN
Este script realiza un escaneo WPScan en la URL especificada.

.SH OPCIONES
.TP
.BI \-u ", \--url" " <url>"
Especifica la URL objetivo para el escaneo.

.SH EJEMPLOS
.B
wpscan http://example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
