.TH CUSTOM_WEB_ENUM 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
custom_web_enum \- Script de enumeración web mejorado
.SH SYNOPSIS
.B custom_web_enum
.RI [ opciones ] " <url>"
.SH DESCRIPCIÓN
Este script realiza una enumeración web mejorada en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-u ", \--url" " <url>"
Especifica la URL objetivo para la enumeración web.

.SH EJEMPLOS
.B
custom_web_enum http://example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
