.TH MARINE_WEB_ENUM 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
marine_web_enum \- Script de enumeración web de Marinesh
.SH SYNOPSIS
.B marine_web_enum
.RI [ opciones ] " <url>"
.SH DESCRIPCIÓN
Este script realiza una enumeración web en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-u ", \--url" " <url>"
Especifica la URL objetivo para la enumeración web.

.SH EJEMPLOS
.B
marine_web_enum http://example.com

.SH AUTOR
Desarrollado por Marinesh.
