.TH MARINE_LDAP_ENUM 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
marine_ldap_enum \- Script de enumeración LDAP de Marinesh
.SH SYNOPSIS
.B marine_ldap_enum
.RI [ opciones ] " <target>"
.SH DESCRIPCIÓN
Este script realiza una enumeración LDAP en el objetivo especificado.

.SH OPCIONES
.TP
.BI \-t ", \--target" " <target>"
Especifica el objetivo de la enumeración.

.SH EJEMPLOS
.B
marine_ldap_enum 192.168.1.1

.SH AUTOR
Desarrollado por Marinesh.
