.TH SUBDOMAIN_ENUM 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
subdomain_enum \- Script personalizado para enumeración de subdominios
.SH SYNOPSIS
.B subdomain_enum
.RI [ opciones ] " <domain>"
.SH DESCRIPCIÓN
Este script realiza una enumeración de subdominios en el dominio especificado.

.SH OPCIONES
.TP
.BI \-d ", \--domain" " <domain>"
Especifica el dominio objetivo para la enumeración de subdominios.

.SH EJEMPLOS
.B
subdomain_enum example.com

.SH AUTOR
Desarrollado por el equipo de red teaming.
